version: '3'

services:
  
  # spring-server:
  #   build:
  #     context: . 
  #     dockerfile: Dockerfile
  #   container_name: pharmserv-spring-server  
  #   ports:
  #     - "8080:8080" 
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db-server:3306/pharmserv-db
  #     SPRING_DATASOURCE_USERNAME: mysql
  #     SPRING_DATASOURCE_PASSWORD: mysql
  #   depends_on:
  #     - db-server 

  db-server:
    image: mysql:8.0.30
    container_name: pharmserv-mysql-server
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmserv-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db-data:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    container_name: pharmserv-db-gui
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db-server
      PMA_PORT: 3306 
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db-server

  # ui:
  #   build:
  #     context: ../Pharmserv-UI
  #     dockerfile: Dockerfile
  #   container_name: pharmserv-ui
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ../Pharmserv-UI:/app  
  #     - /app/node_modules
  #     - ui-build:/build-output  
  #   depends_on:
  #     - db-server
  
  # caddy:
  #   image: caddy:alpine
  #   container_name: pharmserv-caddy
  #   ports:
  #     - "80:80"  
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ui-build:/usr/share/caddy   
  #   depends_on:
  #     - ui     

volumes:
  db-data:
  # ui-build: