services:

  spring-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pharmserv-spring-server-dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-server:3306/pharmserv-db
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      ADMIN_BOOTSTRAP_ENABLED: ${ADMIN_BOOTSTRAP_ENABLED}
      ADMIN_BOOTSTRAP_USER_ID: ${ADMIN_BOOTSTRAP_USER_ID}
      ADMIN_BOOTSTRAP_USERNAME: ${ADMIN_BOOTSTRAP_USERNAME}
      ADMIN_BOOTSTRAP_EMAIL: ${ADMIN_BOOTSTRAP_EMAIL}
      ADMIN_BOOTSTRAP_PASSWORD: ${ADMIN_BOOTSTRAP_PASSWORD}

    volumes:
      - ./src:/app/src
      - ./.mvn:/app/.mvn
      - ./pom.xml:/app/pom.xml
      - ./mvnw:/app/mvnw

    depends_on:
      db-server:
        condition: service_healthy

    restart: unless-stopped


  db-server:
    image: mysql:8.0.30
    container_name: pharmserv-mysql-server-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmserv-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db-data-dev:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pharmserv-db-gui-dev
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      db-server:
        condition: service_healthy
    restart: unless-stopped


  ui:
    build:
      context: ../Pharmserv-UI
      dockerfile: Dockerfile.dev
    container_name: pharmserv-ui-dev
    ports:
      - "4200:4200"
    volumes:
      - ../Pharmserv-UI:/app
      - ui-node-modules:/app/node_modules
    restart: unless-stopped


  caddy:
    image: caddy:alpine
    container_name: pharmserv-caddy-dev
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - spring-server
      - ui
    restart: unless-stopped


volumes:
  db-data-dev:
  ui-node-modules: